Config = {}

-- Standalone BS Race PDM (no SQL / framework)
Config.FreeVehicles = true -- no money required
Config.InteractKey = 38 -- E
Config.InteractDistance = 2.2
Config.MarkerDistance = 25.0
Config.DrawMarker = true
Config.TestDriveSeconds = 45
Config.ShopName = 'PDM // SHOWROOM'
Config.Subtitle = 'VEHICLES // FREE CLAIM'

Config.Blip = {
    enabled = true,
    sprite = 326,
    color = 3,
    scale = 0.8,
    label = 'Premium Deluxe Motorsport',
}

Config.Marker = {
    type = 27,
    scale = vector3(1.2, 1.2, 0.5),
    color = { r = 0, g = 229, b = 255, a = 140 },
    bob = false,
    rotate = true,
}

Config.VehicleShops = {
    [1] = {
        npcSettings = { model = "s_m_y_valet_01", coords = vector4(-56.1483, -1098.3049, 25.4224, 25.9987) },
        blipSettings = { id = 225, colour = 66, scale = 0.65, displayName = "PDM Vehicle Shop" },
        viewVehicleCamCoords = vector4(-46.0137, -1102.0034, 26.4223, 339.1078),
        viewVehicleSpawnCoords = vector4(-43.6994, -1095.7622, 25.7912, 91.4447),
        testDriveCoords = vector4(-877.1189, -3213.9675, 13.9814, 60.3565),
        buyCoords = vector4(-7.8292, -1081.4525, 26.0423, 124.4016),
        testDriveDuration = 10, -- SÃ¼reyi saniye olarak belirtin
    },
    [2] = {
        npcSettings = { model = "s_m_y_valet_01", coords = vector4(2234.66, 2883.4, 47.06, 85.08) },
        blipSettings = { id = 225, colour = 66, scale = 0.65, displayName = "Route 66 PDM" },
        viewVehicleCamCoords = vector4(2227.87, 2873.01, 47.5, 147.89),
        viewVehicleSpawnCoords = vector4(2223.34, 2875.08, 47.64, 109.75),
        testDriveCoords = vector4(2194.3, 2937.98, 46.18, 88.75),
        buyCoords = vector4(2209.21, 2933.61, 47.65, 97.12),
        testDriveDuration = 10, -- SÃ¼reyi saniye olarak belirtin
    },
}

Config.Vehicles = {
    ["Compacts"] = {
        { vehicleModel = "blista",      vehicleName = "Blista",              vehicleStat = "A", vehiclePrice = 400000 },
        { vehicleModel = "brioso",      vehicleName = "Brioso R/A",          vehicleStat = "A", vehiclePrice = 300000 },
        { vehicleModel = "club",        vehicleName = "Club",                vehicleStat = "A", vehiclePrice = 025000 },
        { vehicleModel = "dloader",     vehicleName = "Dilettante",          vehicleStat = "A", vehiclePrice = 275000 },
        { vehicleModel = "dilettante",  vehicleName = "Dilettante",          vehicleStat = "A", vehiclePrice = 230000 },
        { vehicleModel = "dilettante2", vehicleName = "Dilettante Patrol",   vehicleStat = "A", vehiclePrice = 250000 },
        { vehicleModel = "kanjo",       vehicleName = "Blista Kanjo",        vehicleStat = "A", vehiclePrice = 300000 },
        { vehicleModel = "panto",       vehicleName = "Panto",               vehicleStat = "A", vehiclePrice = 150000 },
        { vehicleModel = "prairie",     vehicleName = "Prairie",             vehicleStat = "A", vehiclePrice = 400000 },
        { vehicleModel = "rhapsody",    vehicleName = "Rhapsody",            vehicleStat = "A", vehiclePrice = 160000 },
        { vehicleModel = "brioso2",     vehicleName = "Brioso 300",          vehicleStat = "A", vehiclePrice = 120000 },
        { vehicleModel = "weevil",      vehicleName = "Weevil",              vehicleStat = "A", vehiclePrice = 150000 },
        { vehicleModel = "issi7",       vehicleName = "Issi Sport",          vehicleStat = "A", vehiclePrice = 100000 },
        { vehicleModel = "blista2",     vehicleName = "Blista Compact",      vehicleStat = "A", vehiclePrice = 200000 },
        { vehicleModel = "blista3",     vehicleName = "Blista Go Go Monkey", vehicleStat = "A", vehiclePrice = 150000 },
        { vehicleModel = "brioso3",     vehicleName = "Brioso 300 Widebody", vehicleStat = "A", vehiclePrice = 125000 },
        { vehicleModel = "boor",        vehicleName = "Boor",                vehicleStat = "A", vehiclePrice = 230000 }
    },
    ["Sedans"] = {
        { vehicleModel = "asea",        vehicleName = "Asea",            vehicleStat = "B", vehiclePrice = 350000 },
        { vehicleModel = "asterope",    vehicleName = "Asterope",        vehicleStat = "B", vehiclePrice = 250000 },
        { vehicleModel = "cog55",       vehicleName = "Cognoscenti 55",  vehicleStat = "B", vehiclePrice = 220000 },
        { vehicleModel = "cognoscenti", vehicleName = "Cognoscenti",     vehicleStat = "B", vehiclePrice = 225000 },
        { vehicleModel = "emperor",     vehicleName = "Emperor",         vehicleStat = "B", vehiclePrice = 425000 },
        { vehicleModel = "fugitive",    vehicleName = "Fugitive",        vehicleStat = "B", vehiclePrice = 350000 },
        { vehicleModel = "glendale",    vehicleName = "Glendale",        vehicleStat = "B", vehiclePrice = 340000 },
        { vehicleModel = "glendale2",   vehicleName = "Glendale Custom", vehicleStat = "B", vehiclePrice = 350000 },
        { vehicleModel = "ingot",       vehicleName = "Ingot",           vehicleStat = "B", vehiclePrice = 499900 },
        { vehicleModel = "intruder",    vehicleName = "Intruder",        vehicleStat = "B", vehiclePrice = 500250 },
        { vehicleModel = "premier",     vehicleName = "Premier",         vehicleStat = "B", vehiclePrice = 200000 },
        { vehicleModel = "primo",       vehicleName = "Primo",           vehicleStat = "B", vehiclePrice = 200000 },
        { vehicleModel = "primo2",      vehicleName = "Primo Custom",    vehicleStat = "B", vehiclePrice = 220000 },
        { vehicleModel = "regina",      vehicleName = "Regina",          vehicleStat = "B", vehiclePrice = 340000 },
        { vehicleModel = "stafford",    vehicleName = "Stafford",        vehicleStat = "B", vehiclePrice = 1250000 },
        { vehicleModel = "stanier",     vehicleName = "Stanier",         vehicleStat = "B", vehiclePrice = 300000 },
        { vehicleModel = "stratum",     vehicleName = "Stratum",         vehicleStat = "B", vehiclePrice = 300000 },
        { vehicleModel = "stretch",     vehicleName = "Stretch",         vehicleStat = "B", vehiclePrice = 2500000 },
        { vehicleModel = "superd",      vehicleName = "Super Diamond",   vehicleStat = "B", vehiclePrice = 600000 },
        { vehicleModel = "tailgater",   vehicleName = "Tailgater",       vehicleStat = "B", vehiclePrice = 280000 },
        { vehicleModel = "warrener",    vehicleName = "Warrener",        vehicleStat = "B", vehiclePrice = 150000 },
        { vehicleModel = "washington",  vehicleName = "Washington",      vehicleStat = "B", vehiclePrice = 300000 },
        { vehicleModel = "tailgater2",  vehicleName = "Tailgater S",     vehicleStat = "B", vehiclePrice = 800000 },
        { vehicleModel = "cinquemila",  vehicleName = "Lampadati",       vehicleStat = "B", vehiclePrice = 600000 },
        { vehicleModel = "oracle",      vehicleName = "Oracle",          vehicleStat = "B", vehiclePrice = 500000 },
        { vehicleModel = "schafter2",   vehicleName = "Schafter",        vehicleStat = "B", vehiclePrice = 300000 },
        { vehicleModel = "warrener2",   vehicleName = "Warrener HKR",    vehicleStat = "B", vehiclePrice = 300000 },
        { vehicleModel = "rhinehart",   vehicleName = "Rhinehart",       vehicleStat = "B", vehiclePrice = 500000 },
        { vehicleModel = "eudora",      vehicleName = "Eudora",          vehicleStat = "B", vehiclePrice = 1700000 }
    },
    ["SUVs"] = {
        { vehicleModel = "baller",       vehicleName = "Baller",                  vehicleStat = "C", vehiclePrice = 1000000 },
        { vehicleModel = "baller2",      vehicleName = "Baller II",               vehicleStat = "C", vehiclePrice = 1200000 },
        { vehicleModel = "baller3",      vehicleName = "Baller LE",               vehicleStat = "C", vehiclePrice = 1500000 },
        { vehicleModel = "baller4",      vehicleName = "Baller LE LWB",           vehicleStat = "C", vehiclePrice = 1800000 },
        { vehicleModel = "baller5",      vehicleName = "Baller LE (Armored)",     vehicleStat = "C", vehiclePrice = 2000000 },
        { vehicleModel = "baller6",      vehicleName = "Baller LE LWB (Armored)", vehicleStat = "C", vehiclePrice = 2200000 },
        { vehicleModel = "iwagen",       vehicleName = "Obey I-Wagen",            vehicleStat = "C", vehiclePrice = 2250000 },
        { vehicleModel = "astron",       vehicleName = "Astron",                  vehicleStat = "C", vehiclePrice = 1500000 },
        { vehicleModel = "baller7",      vehicleName = "Baller ST",               vehicleStat = "C", vehiclePrice = 2450000 },
        { vehicleModel = "baller8",      vehicleName = "Baller ST 8",             vehicleStat = "C", vehiclePrice = 2500000 },
        { vehicleModel = "jubilee",      vehicleName = "Jubilee",                 vehicleStat = "C", vehiclePrice = 485000 },
        { vehicleModel = "bjxl",         vehicleName = "BeeJay XL",               vehicleStat = "C", vehiclePrice = 500000 },
        { vehicleModel = "cavalcade",    vehicleName = "Cavalcade",               vehicleStat = "C", vehiclePrice = 700000 },
        { vehicleModel = "cavalcade2",   vehicleName = "Cavalcade II",            vehicleStat = "C", vehiclePrice = 800500 },
        { vehicleModel = "contender",    vehicleName = "Contender",               vehicleStat = "C", vehiclePrice = 900000 },
        { vehicleModel = "dubsta",       vehicleName = "Dubsta",                  vehicleStat = "C", vehiclePrice = 1000000 },
        { vehicleModel = "dubsta2",      vehicleName = "Dubsta Luxury",           vehicleStat = "C", vehiclePrice = 1200000 },
        { vehicleModel = "fq2",          vehicleName = "FQ2",                     vehicleStat = "C", vehiclePrice = 1300000 },
        { vehicleModel = "granger",      vehicleName = "Granger",                 vehicleStat = "C", vehiclePrice = 900000 },
        { vehicleModel = "gresley",      vehicleName = "Gresley",                 vehicleStat = "C", vehiclePrice = 925000 },
        { vehicleModel = "habanero",     vehicleName = "Habanero",                vehicleStat = "C", vehiclePrice = 900000 },
        { vehicleModel = "huntley",      vehicleName = "Huntley S",               vehicleStat = "C", vehiclePrice = 900500 },
        { vehicleModel = "landstalker",  vehicleName = "Landstalker",             vehicleStat = "C", vehiclePrice = 900000 },
        { vehicleModel = "landstalker2", vehicleName = "Landstalker XL",          vehicleStat = "C", vehiclePrice = 900000 },
        { vehicleModel = "novak",        vehicleName = "Novak",                   vehicleStat = "C", vehiclePrice = 750000 },
        { vehicleModel = "patriot",      vehicleName = "Patriot",                 vehicleStat = "C", vehiclePrice = 950000 },
        { vehicleModel = "patriot2",     vehicleName = "Patriot Stretch",         vehicleStat = "C", vehiclePrice = 900000 },
        { vehicleModel = "radi",         vehicleName = "Radius",                  vehicleStat = "C", vehiclePrice = 800000 },
        { vehicleModel = "rebla",        vehicleName = "Rebla GTS",               vehicleStat = "C", vehiclePrice = 900000 },
        { vehicleModel = "rocoto",       vehicleName = "Rocoto",                  vehicleStat = "C", vehiclePrice = 850000 },
        { vehicleModel = "seminole",     vehicleName = "Seminole",                vehicleStat = "C", vehiclePrice = 750000 },
        { vehicleModel = "seminole2",    vehicleName = "Seminole Frontier",       vehicleStat = "C", vehiclePrice = 750000 },
        { vehicleModel = "serrano",      vehicleName = "Serrano",                 vehicleStat = "C", vehiclePrice = 800000 },
        { vehicleModel = "toros",        vehicleName = "Toros",                   vehicleStat = "C", vehiclePrice = 650000 },
        { vehicleModel = "xls",          vehicleName = "XLS",                     vehicleStat = "C", vehiclePrice = 700000 },
        { vehicleModel = "granger2",     vehicleName = "Granger 3600LX",          vehicleStat = "C", vehiclePrice = 800000 },
        { vehicleModel = "patriot3",     vehicleName = "Patriot Military",        vehicleStat = "C", vehiclePrice = 800000 }
    },

    ["Coupes"] = {
        { vehicleModel = "comet7",    vehicleName = "Comet",              vehicleStat = "D", vehiclePrice = 100000 },
        { vehicleModel = "cogcabrio", vehicleName = "Cognoscenti Cabrio", vehicleStat = "D", vehiclePrice = 600000 },
        { vehicleModel = "exemplar",  vehicleName = "Exemplar",           vehicleStat = "D", vehiclePrice = 4000000 },
        { vehicleModel = "f620",      vehicleName = "F620",               vehicleStat = "D", vehiclePrice = 6000000 },
        { vehicleModel = "felon",     vehicleName = "Felon",              vehicleStat = "D", vehiclePrice = 310000 },
        { vehicleModel = "felon2",    vehicleName = "Felon GT",           vehicleStat = "D", vehiclePrice = 470000 },
        { vehicleModel = "jackal",    vehicleName = "Jackal",             vehicleStat = "D", vehiclePrice = 500000 },
        { vehicleModel = "oracle2",   vehicleName = "Oracle XS",          vehicleStat = "D", vehiclePrice = 480000 },
        { vehicleModel = "sentinel",  vehicleName = "Sentinel",           vehicleStat = "D", vehiclePrice = 490000 },
        { vehicleModel = "sentinel2", vehicleName = "Sentinel XS",        vehicleStat = "D", vehiclePrice = 450000 },
        { vehicleModel = "windsor",   vehicleName = "Windsor",            vehicleStat = "D", vehiclePrice = 600000 },
        { vehicleModel = "windsor2",  vehicleName = "Windsor Drop",       vehicleStat = "D", vehiclePrice = 650000 },
        { vehicleModel = "zion",      vehicleName = "Zion",               vehicleStat = "D", vehiclePrice = 550000 },
        { vehicleModel = "zion2",     vehicleName = "Zion Cabrio",        vehicleStat = "D", vehiclePrice = 560000 },
        { vehicleModel = "previon",   vehicleName = "Previon",            vehicleStat = "D", vehiclePrice = 700000 },
        { vehicleModel = "champion",  vehicleName = "Champion",           vehicleStat = "D", vehiclePrice = 650000 },
        { vehicleModel = "futo",      vehicleName = "Futo",               vehicleStat = "D", vehiclePrice = 550500 },
        { vehicleModel = "sentinel3", vehicleName = "Sentinel Classic",   vehicleStat = "D", vehiclePrice = 700000 },
        { vehicleModel = "kanjosj",   vehicleName = "Kanjo SJ",           vehicleStat = "D", vehiclePrice = 500000 },
        { vehicleModel = "postlude",  vehicleName = "Postlude",           vehicleStat = "D", vehiclePrice = 900000 },
        { vehicleModel = "tahoma",    vehicleName = "Tahoma Coupe",       vehicleStat = "D", vehiclePrice = 500000 },
        { vehicleModel = "broadway",  vehicleName = "Broadway",           vehicleStat = "D", vehiclePrice = 1500000 }
    },
    ["Luxury"] = {
        { vehicleModel = 'emperor2',   vehicleName = 'Emperor',                 vehicleStat = "F", vehiclePrice = 2500000 },
        { vehicleModel = 'buccaneer2', vehicleName = 'Buccaneer Rider',         vehicleStat = "F", vehiclePrice = 450000 },
        { vehicleModel = 'chino',      vehicleName = 'Chino',                   vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'chino2',     vehicleName = 'Chino Luxe',              vehicleStat = "F", vehiclePrice = 600000 },
        { vehicleModel = 'clique',     vehicleName = 'Clique',                  vehicleStat = "F", vehiclePrice = 2000000 },
        { vehicleModel = 'coquette3',  vehicleName = 'Coquette BlackFin',       vehicleStat = "F", vehiclePrice = 1800000 },
        { vehicleModel = 'deviant',    vehicleName = 'Deviant',                 vehicleStat = "F", vehiclePrice = 700000 },
        { vehicleModel = 'dominator',  vehicleName = 'Dominator',               vehicleStat = "F", vehiclePrice = 625000 },
        { vehicleModel = 'dominator2', vehicleName = 'PiÃŸwasser Dominator',     vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'dominator3', vehicleName = 'Dominator GTX',           vehicleStat = "F", vehiclePrice = 700000 },
        { vehicleModel = 'dominator7', vehicleName = 'Dominator ASP',           vehicleStat = "F", vehiclePrice = 710000 },
        { vehicleModel = 'dominator8', vehicleName = 'Dominator GTT',           vehicleStat = "F", vehiclePrice = 800000 },
        { vehicleModel = 'dukes',      vehicleName = 'Dukes',                   vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'dukes3',     vehicleName = 'Beater Dukes',            vehicleStat = "F", vehiclePrice = 550000 },
        { vehicleModel = 'faction',    vehicleName = 'Faction',                 vehicleStat = "F", vehiclePrice = 700000 },
        { vehicleModel = 'faction2',   vehicleName = 'Faction Rider',           vehicleStat = "F", vehiclePrice = 650000 },
        { vehicleModel = 'faction3',   vehicleName = 'Faction Custom Donk',     vehicleStat = "F", vehiclePrice = 550000 },
        { vehicleModel = 'ellie',      vehicleName = 'Ellie',                   vehicleStat = "F", vehiclePrice = 422500 },
        { vehicleModel = 'gauntlet',   vehicleName = 'Gauntlet',                vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'gauntlet2',  vehicleName = 'Redwood Gauntlet',        vehicleStat = "F", vehiclePrice = 700000 },
        { vehicleModel = 'gauntlet3',  vehicleName = 'Classic Gauntlet',        vehicleStat = "F", vehiclePrice = 750000 },
        { vehicleModel = 'gauntlet4',  vehicleName = 'Gauntlet Hellfire',       vehicleStat = "F", vehiclePrice = 800000 },
        { vehicleModel = 'gauntlet5',  vehicleName = 'Gauntlet Classic Custom', vehicleStat = "F", vehiclePrice = 120000 },
        { vehicleModel = 'hermes',     vehicleName = 'Hermes',                  vehicleStat = "F", vehiclePrice = 535000 },
        { vehicleModel = 'hotknife',   vehicleName = 'Hotknife',                vehicleStat = "F", vehiclePrice = 700000 },
        { vehicleModel = 'hustler',    vehicleName = 'Hustler',                 vehicleStat = "F", vehiclePrice = 950000 },
        { vehicleModel = 'impaler',    vehicleName = 'Impaler',                 vehicleStat = "F", vehiclePrice = 950000 },
        { vehicleModel = 'lurcher',    vehicleName = 'Lurcher',                 vehicleStat = "F", vehiclePrice = 650000 },
        { vehicleModel = 'nightshade', vehicleName = 'Nightshade',              vehicleStat = "F", vehiclePrice = 700000 },
        { vehicleModel = 'phoenix',    vehicleName = 'Phoenix',                 vehicleStat = "F", vehiclePrice = 650000 },
        { vehicleModel = 'picador',    vehicleName = 'Picador',                 vehicleStat = "F", vehiclePrice = 600000 },
        { vehicleModel = 'ratloader2', vehicleName = 'Ratloader',               vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'ruiner',     vehicleName = 'Ruiner',                  vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'sabregt',    vehicleName = 'Sabre GT Turbo',          vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'sabregt2',   vehicleName = 'Sabre GT Turbo Custom',   vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'slamvan',    vehicleName = 'Slam Van',                vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'stalion',    vehicleName = 'Stallion',                vehicleStat = "F", vehiclePrice = 600000 },
        { vehicleModel = 'stalion2',   vehicleName = 'Stallion Burgershot',     vehicleStat = "F", vehiclePrice = 450000 },
        { vehicleModel = 'tampa',      vehicleName = 'Tampa',                   vehicleStat = "F", vehiclePrice = 450000 },
        { vehicleModel = 'tamp4',      vehicleName = 'Tampa (Custom)',          vehicleStat = "F", vehiclePrice = 450000 },
        { vehicleModel = 'tulip',      vehicleName = 'Tulip',                   vehicleStat = "F", vehiclePrice = 800000 },
        { vehicleModel = 'vamos',      vehicleName = 'Vamos',                   vehicleStat = "F", vehiclePrice = 600000 },
        { vehicleModel = 'vigero',     vehicleName = 'Vigero',                  vehicleStat = "F", vehiclePrice = 500000 },
        { vehicleModel = 'virgo',      vehicleName = 'Virgo',                   vehicleStat = "F", vehiclePrice = 620000 },
        { vehicleModel = 'virgo2',     vehicleName = 'Virgo Custom Classic',    vehicleStat = "F", vehiclePrice = 710000 },
        { vehicleModel = 'virgo3',     vehicleName = 'Virgo Classic',           vehicleStat = "F", vehiclePrice = 801000 },
        { vehicleModel = 'voodoo',     vehicleName = 'Voodoo',                  vehicleStat = "F", vehiclePrice = 800000 },
        { vehicleModel = 'yosemite',   vehicleName = 'Yosemite',                vehicleStat = "F", vehiclePrice = 850000 },
        { vehicleModel = 'yosemite2',  vehicleName = 'Yosemite Drift',          vehicleStat = "F", vehiclePrice = 900000 },
        { vehicleModel = 'buffalo4',   vehicleName = 'Buffalo STX',             vehicleStat = "F", vehiclePrice = 650000 },
        { vehicleModel = 'manana',     vehicleName = 'Manana',                  vehicleStat = "F", vehiclePrice = 800000 },
        { vehicleModel = 'manana2',    vehicleName = 'Manana Custom',           vehicleStat = "F", vehiclePrice = 700000 },
        { vehicleModel = 'tampa2',     vehicleName = 'Drift Tampa',             vehicleStat = "F", vehiclePrice = 800000 },
        { vehicleModel = 'ruiner4',    vehicleName = 'Ruiner ZZ-8',             vehicleStat = "F", vehiclePrice = 850000 }
    },
    ["Sport Classic"] = {
        { vehicleModel = 'ardent',    vehicleName = 'Ardent',              vehicleStat = "M", vehiclePrice = 900000 },
        { vehicleModel = 'btype',     vehicleName = 'Roosevelt',           vehicleStat = "M", vehiclePrice = 750000 },
        { vehicleModel = 'btype2',    vehicleName = 'Franken Stange',      vehicleStat = "M", vehiclePrice = 870000 },
        { vehicleModel = 'btype3',    vehicleName = 'Roosevelt Valor',     vehicleStat = "M", vehiclePrice = 630000 },
        { vehicleModel = 'casco',     vehicleName = 'Casco',               vehicleStat = "M", vehiclePrice = 1000000 },
        { vehicleModel = 'deluxo',    vehicleName = 'Deluxo',              vehicleStat = "M", vehiclePrice = 550000 },
        { vehicleModel = 'dynasty',   vehicleName = 'Dynasty',             vehicleStat = "M", vehiclePrice = 500000 },
        { vehicleModel = 'fagaloa',   vehicleName = 'Fagaloa',             vehicleStat = "M", vehiclePrice = 500000 },
        { vehicleModel = 'feltzer3',  vehicleName = 'Stirling GT',         vehicleStat = "M", vehiclePrice = 580000 },
        { vehicleModel = 'gt500',     vehicleName = 'GT500',               vehicleStat = "M", vehiclePrice = 560000 },
        { vehicleModel = 'infernus2', vehicleName = 'Infernus Classic',    vehicleStat = "M", vehiclePrice = 560000 },
        { vehicleModel = 'jb700',     vehicleName = 'JB 700',              vehicleStat = "M", vehiclePrice = 560000 },
        { vehicleModel = 'jb7002',    vehicleName = 'JB 700W',             vehicleStat = "M", vehiclePrice = 400000 },
        { vehicleModel = 'mamba',     vehicleName = 'Mamba',               vehicleStat = "M", vehiclePrice = 560000 },
        { vehicleModel = 'michelli',  vehicleName = 'Michelli GT',         vehicleStat = "M", vehiclePrice = 480000 },
        { vehicleModel = 'monroe',    vehicleName = 'Monroe',              vehicleStat = "M", vehiclePrice = 500000 },
        { vehicleModel = 'nebula',    vehicleName = 'Nebula',              vehicleStat = "M", vehiclePrice = 650000 },
        { vehicleModel = 'peyote',    vehicleName = 'Peyote',              vehicleStat = "M", vehiclePrice = 500000 },
        { vehicleModel = 'peyote3',   vehicleName = 'Peyote Custom',       vehicleStat = "M", vehiclePrice = 480000 },
        { vehicleModel = 'pigalle',   vehicleName = 'Pigalle',             vehicleStat = "M", vehiclePrice = 920000 },
        { vehicleModel = 'rapidgt3',  vehicleName = 'Rapid GT Classic',    vehicleStat = "M", vehiclePrice = 900000 },
        { vehicleModel = 'retinue',   vehicleName = 'Retinue',             vehicleStat = "M", vehiclePrice = 320000 },
        { vehicleModel = 'retinue2',  vehicleName = 'Retinue MKII',        vehicleStat = "M", vehiclePrice = 380000 },
        { vehicleModel = 'savestra',  vehicleName = 'Savestra',            vehicleStat = "M", vehiclePrice = 670000 },
        { vehicleModel = 'stinger',   vehicleName = 'Stinger',             vehicleStat = "M", vehiclePrice = 595000 },
        { vehicleModel = 'stingergt', vehicleName = 'Stinger GT',          vehicleStat = "M", vehiclePrice = 700000 },
        { vehicleModel = 'stromberg', vehicleName = 'Stromberg',           vehicleStat = "M", vehiclePrice = 800000 },
        { vehicleModel = 'swinger',   vehicleName = 'Swinger',             vehicleStat = "M", vehiclePrice = 681000 },
        { vehicleModel = 'torero',    vehicleName = 'Torero',              vehicleStat = "M", vehiclePrice = 840000 },
        { vehicleModel = 'tornado',   vehicleName = 'Tornado',             vehicleStat = "M", vehiclePrice = 601000 },
        { vehicleModel = 'tornado2',  vehicleName = 'Tornado Convertible', vehicleStat = "M", vehiclePrice = 502000 },
        { vehicleModel = 'tornado5',  vehicleName = 'Tornado Custom',      vehicleStat = "M", vehiclePrice = 502000 },
        { vehicleModel = 'turismo2',  vehicleName = 'Turismo Classic',     vehicleStat = "M", vehiclePrice = 670000 },
        { vehicleModel = 'z190',      vehicleName = '190Z',                vehicleStat = "M", vehiclePrice = 780000 },
        { vehicleModel = 'ztype',     vehicleName = 'Z-Type',              vehicleStat = "M", vehiclePrice = 700000 },
        { vehicleModel = 'zion3',     vehicleName = 'Zion Classic',        vehicleStat = "M", vehiclePrice = 800000 },
        { vehicleModel = 'cheburek',  vehicleName = 'Cheburek',            vehicleStat = "M", vehiclePrice = 700000 },
        { vehicleModel = 'peyote2',   vehicleName = 'Peyote Gasser',       vehicleStat = "M", vehiclePrice = 800000 },
        { vehicleModel = 'coquette2', vehicleName = 'Coquette Classic',    vehicleStat = "M", vehiclePrice = 650000 },
    },

    ["Sports"] = {
        { vehicleModel = 'alpha',     vehicleName = 'Alpha',                vehicleStat = "SP", vehiclePrice = 930000 },
        { vehicleModel = 'banshee',   vehicleName = 'Banshee',              vehicleStat = "SP", vehiclePrice = 1000000 },
        { vehicleModel = 'bestiagts', vehicleName = 'Bestia GTS',           vehicleStat = "SP", vehiclePrice = 700000 },
        { vehicleModel = 'buffalo',   vehicleName = 'Buffalo',              vehicleStat = "SP", vehiclePrice = 750000 },
        { vehicleModel = 'buffalo2',  vehicleName = 'Buffalo S',            vehicleStat = "SP", vehiclePrice = 790000 },
        { vehicleModel = 'comet2',    vehicleName = 'Comet',                vehicleStat = "SP", vehiclePrice = 1300000 },
        { vehicleModel = 'comet3',    vehicleName = 'Comet Retro Custom',   vehicleStat = "SP", vehiclePrice = 1750000 },
        { vehicleModel = 'comet4',    vehicleName = 'Comet Safari',         vehicleStat = "SP", vehiclePrice = 1900000 },
        { vehicleModel = 'comet5',    vehicleName = 'Comet SR',             vehicleStat = "SP", vehiclePrice = 2000000 },
        { vehicleModel = 'coquette',  vehicleName = 'Coquette',             vehicleStat = "SP", vehiclePrice = 1250000 },
        { vehicleModel = 'coquette4', vehicleName = 'Coquette D10',         vehicleStat = "SP", vehiclePrice = 2200000 },
        { vehicleModel = 'drafter',   vehicleName = '8F Drafter',           vehicleStat = "SP", vehiclePrice = 1400000 },
        { vehicleModel = 'elegy',     vehicleName = 'Elegy Retro Custom',   vehicleStat = "SP", vehiclePrice = 1450000 },
        { vehicleModel = 'elegy2',    vehicleName = 'Elegy RH8',            vehicleStat = "SP", vehiclePrice = 1500000 },
        { vehicleModel = 'flashgt',   vehicleName = 'Flash GT',             vehicleStat = "SP", vehiclePrice = 999000 },
        { vehicleModel = 'furoregt',  vehicleName = 'Furore GT',            vehicleStat = "SP", vehiclePrice = 780000 },
        { vehicleModel = 'gb200',     vehicleName = 'GB 200',               vehicleStat = "SP", vehiclePrice = 1400000 },
        { vehicleModel = 'komoda',    vehicleName = 'Komoda',               vehicleStat = "SP", vehiclePrice = 750000 },
        { vehicleModel = 'imorgon',   vehicleName = 'Imorgon',              vehicleStat = "SP", vehiclePrice = 1200000 },
        { vehicleModel = 'italigto',  vehicleName = 'Itali GTO',            vehicleStat = "SP", vehiclePrice = 2600000 },
        { vehicleModel = 'jugular',   vehicleName = 'Jugular',              vehicleStat = "SP", vehiclePrice = 1600000 },
        { vehicleModel = 'jester',    vehicleName = 'Jester',               vehicleStat = "SP", vehiclePrice = 1322050 },
        { vehicleModel = 'jester2',   vehicleName = 'Jester Racecar',       vehicleStat = "SP", vehiclePrice = 1410000 },
        { vehicleModel = 'jester3',   vehicleName = 'Jester Classic',       vehicleStat = "SP", vehiclePrice = 1505000 },
        { vehicleModel = 'khamelion', vehicleName = 'Khamelion',            vehicleStat = "SP", vehiclePrice = 1000000 },
        { vehicleModel = 'kuruma',    vehicleName = 'Kuruma',               vehicleStat = "SP", vehiclePrice = 992000 },
        { vehicleModel = 'locust',    vehicleName = 'Locust',               vehicleStat = "SP", vehiclePrice = 800000 },
        { vehicleModel = 'lynx',      vehicleName = 'Lynx',                 vehicleStat = "SP", vehiclePrice = 1500000 },
        { vehicleModel = 'massacro',  vehicleName = 'Massacro',             vehicleStat = "SP", vehiclePrice = 1100000 },
        { vehicleModel = 'massacro2', vehicleName = 'Massacro Racecar',     vehicleStat = "SP", vehiclePrice = 800000 },
        { vehicleModel = 'neo',       vehicleName = 'Neo',                  vehicleStat = "SP", vehiclePrice = 2300000 },
        { vehicleModel = 'neon',      vehicleName = 'Neon',                 vehicleStat = "SP", vehiclePrice = 2200000 },
        { vehicleModel = 'ninef',     vehicleName = '9F',                   vehicleStat = "SP", vehiclePrice = 950000 },
        { vehicleModel = 'ninef2',    vehicleName = '9F Cabrio',            vehicleStat = "SP", vehiclePrice = 1050000 },
        { vehicleModel = 'omnis',     vehicleName = 'Omnis',                vehicleStat = "SP", vehiclePrice = 900000 },
        { vehicleModel = 'paragon',   vehicleName = 'Paragon',              vehicleStat = "SP", vehiclePrice = 900000 },
        { vehicleModel = 'pariah',    vehicleName = 'Pariah',               vehicleStat = "SP", vehiclePrice = 900000 },
        { vehicleModel = 'penumbra',  vehicleName = 'Penumbra',             vehicleStat = "SP", vehiclePrice = 802000 },
        { vehicleModel = 'penumbra2', vehicleName = 'Penumbra FF',          vehicleStat = "SP", vehiclePrice = 900000 },
        { vehicleModel = 'rapidgt',   vehicleName = 'Rapid GT',             vehicleStat = "SP", vehiclePrice = 860000 },
        { vehicleModel = 'rapidgt2',  vehicleName = 'Rapid GT Convertible', vehicleStat = "SP", vehiclePrice = 920000 },
        { vehicleModel = 'raptor',    vehicleName = 'Raptor',               vehicleStat = "SP", vehiclePrice = 900000 },
        { vehicleModel = 'revolter',  vehicleName = 'Revolter',             vehicleStat = "SP", vehiclePrice = 950000 },
        { vehicleModel = 'ruston',    vehicleName = 'Ruston',               vehicleStat = "SP", vehiclePrice = 1300000 },
        { vehicleModel = 'schafter3', vehicleName = 'Schafter V12',         vehicleStat = "SP", vehiclePrice = 850000 },
        { vehicleModel = 'schafter4', vehicleName = 'Schafter LWB',         vehicleStat = "SP", vehiclePrice = 999000 },
        { vehicleModel = 'schlagen',  vehicleName = 'Schlagen GT',          vehicleStat = "SP", vehiclePrice = 1600000 },
        { vehicleModel = 'schwarzer', vehicleName = 'Schwartzer',           vehicleStat = "SP", vehiclePrice = 907000 },
        { vehicleModel = 'seven70',   vehicleName = 'Seven-70',             vehicleStat = "SP", vehiclePrice = 140000 },
        { vehicleModel = 'specter',   vehicleName = 'Specter',              vehicleStat = "SP", vehiclePrice = 1600000 },
        { vehicleModel = 'streiter',  vehicleName = 'Streiter',             vehicleStat = "SP", vehiclePrice = 800000 },
        { vehicleModel = 'sugoi',     vehicleName = 'Sugoi',                vehicleStat = "SP", vehiclePrice = 850000 },
        { vehicleModel = 'sultan',    vehicleName = 'Sultan',               vehicleStat = "SP", vehiclePrice = 1000000 },
        { vehicleModel = 'sultan2',   vehicleName = 'Sultan Custom',        vehicleStat = "SP", vehiclePrice = 1300000 },
        { vehicleModel = 'surano',    vehicleName = 'Surano',               vehicleStat = "SP", vehiclePrice = 800000 }
    },

    ["Starter"] = {
        { vehicleModel = 'buffalo', vehicleName = "Buffalo",     vehicleStat = "S", vehiclePrice = 0 },
        { vehicleModel = 'surge',   vehicleName = "Power Surge", vehicleStat = "S", vehiclePrice = 0 }
    },

    ["Motorcycle"] = {
        { vehicleModel = 'akuma',       vehicleName = 'Akuma',                 vehicleStat = "O", vehiclePrice = 550000 },
        { vehicleModel = 'avarus',      vehicleName = 'Avarus',                vehicleStat = "O", vehiclePrice = 200000 },
        { vehicleModel = 'bagger',      vehicleName = 'Bagger',                vehicleStat = "O", vehiclePrice = 135000 },
        { vehicleModel = 'bati',        vehicleName = 'Bati 801',              vehicleStat = "O", vehiclePrice = 1500000 },
        { vehicleModel = 'bati2',       vehicleName = 'Bati 801RR',            vehicleStat = "O", vehiclePrice = 190000 },
        { vehicleModel = 'bf400',       vehicleName = 'BF400',                 vehicleStat = "O", vehiclePrice = 220000 },
        { vehicleModel = 'carbonrs',    vehicleName = 'Carbon RS',             vehicleStat = "O", vehiclePrice = 220000 },
        { vehicleModel = 'chimera',     vehicleName = 'Chimera',               vehicleStat = "O", vehiclePrice = 210000 },
        { vehicleModel = 'cliffhanger', vehicleName = 'Cliffhanger',           vehicleStat = "O", vehiclePrice = 285000 },
        { vehicleModel = 'daemon',      vehicleName = 'Daemon',                vehicleStat = "O", vehiclePrice = 140000 },
        { vehicleModel = 'daemon2',     vehicleName = 'Daemon Custom',         vehicleStat = "O", vehiclePrice = 230000 },
        { vehicleModel = 'defiler',     vehicleName = 'Defiler',               vehicleStat = "O", vehiclePrice = 300000 },
        { vehicleModel = 'diablous',    vehicleName = 'Diablous',              vehicleStat = "O", vehiclePrice = 300000 },
        { vehicleModel = 'diablous2',   vehicleName = 'Diablous Custom',       vehicleStat = "O", vehiclePrice = 380000 },
        { vehicleModel = 'double',      vehicleName = 'Double-T',              vehicleStat = "O", vehiclePrice = 280000 },
        { vehicleModel = 'enduro',      vehicleName = 'Enduro',                vehicleStat = "O", vehiclePrice = 550000 },
        { vehicleModel = 'esskey',      vehicleName = 'Esskey',                vehicleStat = "O", vehiclePrice = 120000 },
        { vehicleModel = 'faggio',      vehicleName = 'Faggio Sport',          vehicleStat = "O", vehiclePrice = 100000 },
        { vehicleModel = 'fcr',         vehicleName = 'FCR 1000',              vehicleStat = "O", vehiclePrice = 500000 },
        { vehicleModel = 'fcr2',        vehicleName = 'FCR 1000 Custom',       vehicleStat = "O", vehiclePrice = 550000 },
        { vehicleModel = 'gargoyle',    vehicleName = 'Gargoyle',              vehicleStat = "O", vehiclePrice = 320000 },
        { vehicleModel = 'hakuchou',    vehicleName = 'Hakuchou',              vehicleStat = "O", vehiclePrice = 1000000 },
        { vehicleModel = 'hakuchou2',   vehicleName = 'Hakuchou Drag',         vehicleStat = "O", vehiclePrice = 1300000 },
        { vehicleModel = 'hexer',       vehicleName = 'Hexer',                 vehicleStat = "O", vehiclePrice = 160000 },
        { vehicleModel = 'innovation',  vehicleName = 'Innovation',            vehicleStat = "O", vehiclePrice = 335000 },
        { vehicleModel = 'lectro',      vehicleName = 'Lectro',                vehicleStat = "O", vehiclePrice = 280000 },
        { vehicleModel = 'manchez',     vehicleName = 'Manchez',               vehicleStat = "O", vehiclePrice = 630000 },
        { vehicleModel = 'nemesis',     vehicleName = 'Nemesis',               vehicleStat = "O", vehiclePrice = 200000 },
        { vehicleModel = 'nightblade',  vehicleName = 'Nightblade',            vehicleStat = "O", vehiclePrice = 230000 },
        { vehicleModel = 'pcj',         vehicleName = 'PCJ-600',               vehicleStat = "O", vehiclePrice = 1500000 },
        { vehicleModel = 'ratbike',     vehicleName = 'Rat Bike',              vehicleStat = "O", vehiclePrice = 300000 },
        { vehicleModel = 'ruffian',     vehicleName = 'Ruffian',               vehicleStat = "O", vehiclePrice = 250000 },
        { vehicleModel = 'sanchez',     vehicleName = 'Sanchez Livery',        vehicleStat = "O", vehiclePrice = 730000 },
        { vehicleModel = 'sanchez2',    vehicleName = 'Sanchez',               vehicleStat = "O", vehiclePrice = 750000 },
        { vehicleModel = 'sanctus',     vehicleName = 'Sanctus',               vehicleStat = "O", vehiclePrice = 350000 },
        { vehicleModel = 'sovereign',   vehicleName = 'Sovereign',             vehicleStat = "O", vehiclePrice = 500000 },
        { vehicleModel = 'stryder',     vehicleName = 'Stryder',               vehicleStat = "O", vehiclePrice = 500000 },
        { vehicleModel = 'thrust',      vehicleName = 'Thrust',                vehicleStat = "O", vehiclePrice = 220000 },
        { vehicleModel = 'vader',       vehicleName = 'Vader',                 vehicleStat = "O", vehiclePrice = 720000 },
        { vehicleModel = 'vindicator',  vehicleName = 'Vindicator',            vehicleStat = "O", vehiclePrice = 350000 },
        { vehicleModel = 'vortex',      vehicleName = 'Vortex',                vehicleStat = "O", vehiclePrice = 310000 },
        { vehicleModel = 'wolfsbane',   vehicleName = 'Wolfsbane',             vehicleStat = "O", vehiclePrice = 140000 },
        { vehicleModel = 'manchez2',    vehicleName = 'Manchez Scout',         vehicleStat = "O", vehiclePrice = 540000 },
        { vehicleModel = 'shinobi',     vehicleName = 'Shinobi',               vehicleStat = "O", vehiclePrice = 250000 },
        { vehicleModel = 'reever',      vehicleName = 'Reever',                vehicleStat = "O", vehiclePrice = 250000 },
        { vehicleModel = 'manchez3',    vehicleName = 'Manchez Scout Classic', vehicleStat = "O", vehiclePrice = 150000 },
    },
    ["Offroad"] = {
        { vehicleModel = 'bifta',       vehicleName = 'Bifta',             vehicleStat = "H", vehiclePrice = 155000,  shop = 'pdm' },
        { vehicleModel = 'blazer',      vehicleName = 'Blazer',            vehicleStat = "H", vehiclePrice = 550000,  shop = 'pdm' },
        { vehicleModel = 'brawler',     vehicleName = 'Brawler',           vehicleStat = "H", vehiclePrice = 400000,  shop = 'pdm' },
        { vehicleModel = 'dubsta3',     vehicleName = 'Dubsta 6x6',        vehicleStat = "H", vehiclePrice = 1500000, shop = 'pdm' },
        { vehicleModel = 'everon',      vehicleName = 'Everon',            vehicleStat = "H", vehiclePrice = 3000000, shop = 'pdm' },
        { vehicleModel = 'kamacho',     vehicleName = 'Kamacho',           vehicleStat = "H", vehiclePrice = 500000,  shop = 'pdm' },
        { vehicleModel = 'mesa3',       vehicleName = 'Mesa Merryweather', vehicleStat = "H", vehiclePrice = 400000,  shop = 'pdm' },
        { vehicleModel = 'rancherxl',   vehicleName = 'Rancher XL',        vehicleStat = "H", vehiclePrice = 240000,  shop = 'pdm' },
        { vehicleModel = 'rebel2',      vehicleName = 'Rebel',             vehicleStat = "H", vehiclePrice = 200000,  shop = 'pdm' },
        { vehicleModel = 'riata',       vehicleName = 'Riata',             vehicleStat = "H", vehiclePrice = 380000,  shop = 'pdm' },
        { vehicleModel = 'sandking',    vehicleName = 'Sandking XL',       vehicleStat = "H", vehiclePrice = 250000,  shop = 'pdm' },
        { vehicleModel = 'sandking2',   vehicleName = 'Sandking SWB',      vehicleStat = "H", vehiclePrice = 380000,  shop = 'pdm' },
        { vehicleModel = 'vagrant',     vehicleName = 'Vagrant',           vehicleStat = "H", vehiclePrice = 500000,  shop = 'pdm' },
        { vehicleModel = 'verus',       vehicleName = 'Verus',             vehicleStat = "H", vehiclePrice = 200000,  shop = 'pdm' },
        { vehicleModel = 'winky',       vehicleName = 'Winky',             vehicleStat = "H", vehiclePrice = 100000,  shop = 'pdm' },
        { vehicleModel = 'yosemite3',   vehicleName = 'Yosemite Rancher',  vehicleStat = "H", vehiclePrice = 425000,  shop = 'pdm' },
        { vehicleModel = 'mesa',        vehicleName = 'Mesa',              vehicleStat = "H", vehiclePrice = 120000,  shop = 'pdm' },
        { vehicleModel = 'ratel',       vehicleName = 'Ratel',             vehicleStat = "H", vehiclePrice = 350000,  shop = 'pdm' },
        { vehicleModel = 'l35',         vehicleName = 'Walton L35',        vehicleStat = "H", vehiclePrice = 567000,  shop = 'pdm' },
        { vehicleModel = 'monstrociti', vehicleName = 'MonstroCiti',       vehicleStat = "H", vehiclePrice = 480000,  shop = 'pdm' },
        { vehicleModel = 'draugur',     vehicleName = 'Draugur',           vehicleStat = "H", vehiclePrice = 990000,  shop = 'pdm' }
    },
    ["Job"] = {
        { vehicleModel = 'polgauntlet', vehicleName = 'Police gauntlet', vehicleStat = "F", vehiclePrice = 0, shop = 'pdm' },
        { vehicleModel = 'police',      vehicleName = 'Police',          vehicleStat = "F", vehiclePrice = 0, shop = 'pdm' }
    },
    ["Imports"] = {
        { vehicleModel = 'jester4', vehicleName = 'Jester 4', vehicleStat = "F", vehiclePrice = 1200000, shop = 'pdm' },
    }
}

